name: CI Checks

on:
  push

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
